version: '3'
services:
  app:
    image: codexten/ionic
    volumes:
      - /projects:/projects
    working_dir: /projects
#    ports:
#      - "8100:8100"
#    command: ["/usr/local/bin/ionic", "serve", "--no-open"]