version: '3'
services:
  app:
    build: .
#    image: codexten/ionic
#    image: agileek/ionic-framework
    volumes:
      - /projects:/projects
    working_dir: /projects
#    environment:
#      - IONIC_VERSION=5.2.8
    ports:
      - 8100:8100
#    command: ["tail -f /dev/null"]